# .github/workflows/on_pull_request.yml
name: Analyze Image on PR

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install boto3

      - name: Run image analysis for PR (Beta)
        run: |
          for file in images/*.{jpg,png}; do
            python analyze_image.py "$file" beta
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          DYNAMODB_TABLE_BETA: ${{ secrets.DYNAMODB_TABLE_BETA }}
        run: |
          python analyze_image.py
